services:
  plantmontana:
    build: .
    container_name: plantmontana
    restart: unless-stopped
    volumes:
      - plantmontana-data:/app/data
    labels:
      - "traefik.http.services.plantmontana.loadbalancer.server.port=3000"
    networks:
      - traefik-proxy

volumes:
  plantmontana-data:

networks:
  traefik-proxy:
    external: true
